config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root to: "spots#index"
resources :users, only:[:show]
resources :spots, only: [:new, :create,:show,:edit,:update,:destroy] do
 resources :comments, only: [:create]
 
end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
 
  validates :user, presence: true
  validates :spot, presence: true
  validates :text, presence: true

  belongs_to :user, optional: true
  belongs_to :spot, optional: true

end

app/models/spot.rb
class Spot < ApplicationRecord
  
  validates :name, presence: true
  validates :add, presence: true
  validates :note, presence: true
  validates :image, presence: true
  
  belongs_to :user
  has_many :comments,dependent: :destroy
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  validates :profile, presence: true
  validates :occupation, presence: true
  validates :position, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :spots
         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:profile,:occupation,:position])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to spot_path(@comment.spot)
    else
      @spot = @comment.spot
      @comments = @spot.comments
      render "spots/show" 

    end
  end

  private

 def comment_params
   params.require(:comment).permit(:text).merge(user_id: current_user.id, spot_id: params[:spot_id])
 end

end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
 def index
   @spots = Spot.all
  
  
 end

 def show
   @spot = Spot.find(params[:id])
   @comment = Comment.new 
   @comments = @spot.comments.includes(:user)

 end


 def edit
 @spot = Spot.find(params[:id])
 unless  @spot.user_id == current_user.id
  redirect_to action: :index
  
  end


 end

 def destroy
  spot = Spot.find(params[:id])

  spot.destroy

  redirect_to root_path
 end


 def update
  @spot = Spot.find(params[:id])
     
  if @spot.update(spot_params)

     redirect_to  spot_path

   else
     render :edit

  end


 end

 def new

  @spot = Spot.new

 end

 def create
  @spot = Spot.new(spot_params)
    if @spot.save
      redirect_to root_path
    else
      render :new
    end
    
  end

  


 
 private

 def spot_params
   params.require(:spot).permit(:name,:add,:note,:image).merge(user_id: current_user.id)
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @spots = @user.spots

    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Buskers Pradise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
          <h1 class="grid-6"><a href="/">Buskers Paradise</a></h1>
            <%# <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <%# ログインしているときは以下を表示するようにしましょう %>
           <% if user_signed_in? %>
             <div class="nav__right"> 
               <%= link_to "ログアウト", destroy_user_session_path, method:  :delete, class: :nav__logout %>
               <%= link_to "Post busking point",new_spot_path , class: :nav__btn %>
             </div> 
          <%# // ログインしているときは上記を表示するようにしましょう %>
          <%# ログインしていないときは以下を表示するようにしましょう %>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
            <% end %>
          <%# // ログインしていないときは上記を表示するようにしましょう %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © Buskers Paradise All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/prototypes/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
      <div class="greeting"> 
        <div>こんにちは、
        <%= link_to "#{current_user.name}さん", "/users/#{current_user.id}", class: :greeting__link%>
        </div>
      </div> 
    <%end%>
    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
       <%= render partial: "prototype", collection: @prototypes %>
    </div>
  </div>
</main>

app/views/prototypes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
      <%= render partial: "form", locals: { prototype: @prototype } %>

        <%# 部分テンプレートでフォームを表示する %>
    </div>
  </div>
</div>

app/views/prototypes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @prototype.title %>
      </p>
       <%= link_to "by #{@prototype.user.name}",user_path(@prototype.user, method: :get, class: :prototype__user) %>

      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <% if user_signed_in? && current_user.id == @prototype.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_prototype_path(@prototype.id), class: :prototype__btn %>
          <%= link_to "削除する", prototype_path(@prototype.id), class: :prototype__btn, method: :delete %>
        </div>
      <% end %>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="prototype__image">
        <span><%= image_tag (@prototype.image) %></span>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @prototype.catch_copy %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @prototype.concept %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
        <% if user_signed_in? %>
           <%= form_with(model: [@prototype, @comment],local:true) do |f|%>
            <div class="field">
              <br ><%= f.label :text, "コメント" %><br />
              <%= f.text_field :text %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %> 
        <%end%>
        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
             <% @comments.each do |comment| %>
             <li class="comments_list">
               <%= comment.text %>
              <%= link_to "#{comment.user.name}", "/users/#{comment.user.id}", class: :comment_user %>
         
              </li>
             <%end%>
          
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>

      </div>
    </div>
  </div>
</main>

app/views/spots/_form.html.erb
<%= form_with model: spot, local: true do |f| %>
  <div class="field">
    <%= f.label :name, "スポットの名称" %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :add, "住所" %><br />
    <%= f.text_area :add, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :note, "詳細・注意事項" %><br />
    <%= f.text_area :note, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :image, "バスキングポイントの写真" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/spots/_spot.html.erb
<div class="card">
  <%= link_to image_tag(spot.image, class: :card__img), spot_path(spot.id), method: :get %>  
  <div class="card__body">
    <%= link_to spot.name, spot_path(spot.id), class: :card__title%>
    <p class="card__summary">
      <%= spot.add %>
    </p>
    <%= link_to "by #{spot.user.name}",user_path(spot.user, method: :get, class: :card__user) %>
  </div>
</div>

app/views/spots/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">スポット編集</h2>
      <%= render partial: "form", locals: { spot: @spot } %>

    </div>
  </div>
</div>

app/views/spots/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
      <div class="greeting"> 
        <div>こんにちは、
        <%= link_to "#{current_user.name}さん", "/users/#{current_user.id}", class: :greeting__link%>
        </div>
      </div> 
    <%end%>
    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
       <%= render partial: "spot", collection: @spots %>
    </div>
  </div>
</main>

app/views/spots/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規バスキングスポット投稿</h2>
      <%= render partial: "form", locals: { spot: @spot } %>

        <%# 部分テンプレートでフォームを表示する %>
    </div>
  </div>
</div>

app/views/spots/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @spot.name %>
      </p>
       <%= link_to "by #{@spot.user.name}",user_path(@spot.user, method: :get, class: :prototype__user) %>

      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <% if user_signed_in? && current_user.id == @spot.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_spot_path(@spot.id), class: :prototype__btn %>
          <%= link_to "削除する", spot_path(@spot.id), class: :prototype__btn, method: :delete %>
        </div>
      <% end %>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="prototype__image">
        <span><%= image_tag (@spot.image) %></span> 
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">住所</p>
          <p class="detail__message">
            <%= @spot.add %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">詳細</p>
          <p class="detail__message">
            <%= @spot.note %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
        <% if user_signed_in? %>
           <%= form_with(model: [@spot, @comment],local:true) do |f|%>
            <div class="field">
              <br ><%= f.label :text, "予約・現地情報" %><br />
              <%= f.text_area :text,size:"60x5"%>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %> 
        <%end%>
        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
             <% @comments.each do |comment| %>
             <li class="comments_list">
               <%= comment.text %>
              <%= link_to "#{comment.user.name}", "/users/#{comment.user.id}", class: :comment_user %>
         
              </li>
             <%end%>
          
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>

      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.name}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name%></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2"><%= @user.occupation %></td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%= @user.position %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}さんのプロトタイプ"%>
      </h2>
      <div class="user__card">
        <%# 部分テンプレートでそのユーザーが投稿したプロトタイプ投稿一覧を表示する %>
          <%= render partial: "spots/spot", collection: @spots%>
      </div>
    </div>
  </div>
</div>